openapi: 3.0.0
info:
  title: Flask API
  version: 1.0.0
  description: This is a simple Flask API.
servers:
  - url: http://localhost:5000
paths:
  /:
    get:
      summary: Home endpoint
      description: Endpoint to get the home page
      responses:
        '200':
          description: Successful response
  /about:
    get:
      summary: About endpoint
      description: Endpoint to get the about page
      responses:
        '200':
          description: Successful response
  /skills:
    get:
      summary: Skills endpoint
      description: Endpoint to get the skills page
      responses:
        '200':
          description: Successful response
  /projects:
    get:
      summary: Projects endpoint
      description: Endpoint to get the projects page
      responses:
        '200':
          description: Successful response
  /experience:
    get:
      summary: Experience endpoint
      description: Endpoint to get the experience page
      responses:
        '200':
          description: Successful response
  /education:
    get:
      summary: Education endpoint
      description: Endpoint to get the education page
      responses:
        '200':
          description: Successful response
  /contact:
    get:
      summary: Contact endpoint
      description: Endpoint to get the contact page
      responses:
        '200':
          description: Successful response
